### ISSUE TITLE
Add support for GTIN validation besides UPC-A

### ISSUE THREAD

**Issue by austinhartzheim** [austinhartzheim/rigidity#2]
Rigidity already has rules that support validating UPC-A codes.

We want to add support for:
- GTIN-8
- GTIN-12 (UPC-A)
- GTIN-13 (EAN-13)
- GTIN-14

The actual implementation should be very similar across all of these GTIN types.

We will likely want to alias `UpcA` to `Gtin13` and `Ean13` to `Gtin13` to maintain backward compatibility for the already-existing UpcA rule.

The code for these rules should be placed in [rigidity/rules.py](https://github.com/austinhartzheim/rigidity/blob/master/rigidity/rules.py). You may reference the `UpcA` class already in that file.
# Tasks
- [ ] Add Gtin8 class
- [ ] Rename UpcA class to Gtin12 class and add an alias.
- [ ] Add a Gtin13 class and add a Ean13 alias.
- [ ] Add a Gtin14 class.
- [ ] Add test cases for all GTIN code types
# Resources
- [Check Digit Calculator](http://www.gs1.org/check-digit-calculator) - use this for generating test cases
- [UPC-A on Wikipedia](https://en.wikipedia.org/wiki/UPC-A#Check_digit_calculation) - reference the section about the check-digit algorithm
# Hacktoberfest

If you plan to work on this issue as part of Hacktoberfest, please let us know so we can assign the issue to you and avoid duplicate effort. Feel free to bring a friend!
